## 1. 벡터화 연산
반복문(loop)를 사용하지 않고 선형대수의 벡터 or 행렬 연산과 유사한 코드를 사용

### 1-1. 반복문처리
벡터화 연산을 사용하지 않으면, 다음과 같이 반복문을 사용하여야한다

In [2]:
import numpy as np
x = np.arange(1, 1001)
y = np.arange(1001, 2001)

In [3]:
%%time
z=np.zeros_like(x)
for i in range(1000):
    z[i]=x[i] + y[i]

Wall time: 998 µs


In [5]:
z[:10]   

array([1002, 1004, 1006, 1008, 1010, 1012, 1014, 1016, 1018, 1020])

### 1-2. 벡터화연산
그러나 벡터화 연산을 사용하면 덧셈연산 하나면 된다. (위에서 보인 선형 대선의 벡터 기호를 사용한 연산코드와 동일하다)
처리속도도 훨씬 빠르다

In [6]:
%%time
z=x+y
z

Wall time: 0 ns


### 1-3. 비교연산도 벡터화 연산 가능

In [7]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])

In [8]:
a==b

array([False,  True, False,  True], dtype=bool)

In [9]:
a<=b

array([ True,  True, False,  True], dtype=bool)

### 1-4. all
배열전체 비교

In [10]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
c = np.array([1, 2, 3, 4])

In [11]:
np.all(a==b)

False

In [12]:
np.all(a==c)

True

### 1-5. 지수함수, 로그함수 등의 수학함수도 벡터화 연산지원

In [13]:
a = np.arange(5)

np.exp(a)

array([  1.        ,   2.71828183,   7.3890561 ,  20.08553692,  54.59815003])

In [14]:
10 ** a

array([    1,    10,   100,  1000, 10000], dtype=int32)

***
## 2. 스칼라와 벡터  /  행렬곱셈
스칼라와 벡터, 행렬곱셈 역시 선형대숭서 사용하는 식과 numpy코드 일치

In [17]:
x = np.arange(10)
100 * x

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [18]:
x = np.arange(12).reshape(3, 4)
100 * x

array([[   0,  100,  200,  300],
       [ 400,  500,  600,  700],
       [ 800,  900, 1000, 1100]])

***
## 3. 브로드캐스팅
* 선형대수에서는 벡터끼리(행렬끼리) 덧셈,뺄셈을 하려면 두 벡터(두 행렬)의 크기는 같아야 한다  (벡터와 스칼라를 더하는 연산, 선형대수에서는 불가능)
* 하지만 numpy에서는 서로다른 크기를 가진 배열의 사칙연산 지원. 이 기능을 브로드캐스팅
* 크기가 작은 배열을 자동으로 반복확장하여 크기가 큰 배열에 맞추는 방법(스칼라를 벡터와 같은 크기로 확장)

In [19]:
x=np.arange(5)
y=np.ones_like(x)

In [20]:
x+y

array([1, 2, 3, 4, 5])

In [21]:
x+1

array([1, 2, 3, 4, 5])

In [22]:
a = np.tile(np.arange(0, 40, 10), (3, 1)).T
a

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [23]:
b=np.array( [0,1,2])
b

array([0, 1, 2])

In [24]:
a+b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [25]:
a = np.arange(0, 40, 10)[:, np.newaxis]
a

array([[ 0],
       [10],
       [20],
       [30]])

In [26]:
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

***
## 4. 차원축소연산
* 행렬의 하나의 행에 있는 원소들을 하나의 데이터집합으로 보고 그 집합의 평균을 구하면 각 행에 대한 하나의 숫자가 나온다.
* 10x5 크기의 2차원 배열에 대해 행-평균을 구하면 10개의 숫자를 가진 1차원벡터가 구해진다.

### 4-1. 최대,최소 메소드 : min, max, argmin, argmax

In [28]:
x = np.array([1, 3, 2])
x.min()

1

In [29]:
x.max()

3

In [30]:
x.argmin()  #최소값의 위치

0

In [31]:
x.argmax() # 최대값의 위치

1

### 4-2. 통계 : sum, mean, median, std, var

In [33]:
x=np.array([1,2,3,4])
np.sum(x)  # x.sum()

10

In [34]:
x = np.array([1, 2, 3, 1])
x.mean()

1.75

In [35]:
np.median(x)

1.5

### 4-3. 불리언 : all, any

In [36]:
np.all([True, True, False])

False

In [37]:
np.any([True, True, False])

True

In [38]:
a = np.zeros((100, 100), dtype=np.int)
a

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ..., 
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [39]:
np.any(a!=0)

False

In [40]:
np.all(a==a)

True

In [42]:
a = np.array([1, 2, 3, 2])
b = np.array([2, 2, 3, 2])
c = np.array([6, 4, 4, 5])

((a <= b) & (b <= c)).all()

True

### 4-4. 연산대상이 2차원 이상인 경우에는 어느 차원으로 계산 할 지 axis인수로 지시

In [43]:
x = np.array([[1, 1], [2, 2]])
x

array([[1, 1],
       [2, 2]])

In [44]:
x.sum() #원소 하나하나 합

6

In [45]:
x.sum(axis=0) #행끼리 합 (하나의 열에서 합계)

array([3, 3])

In [46]:
x.sum(axis=1) #열끼리 합 (하나의 행에서)

array([2, 4])

****
## 5. 정렬
### 5-1. sort
* 배열 안의 원소를 크기에 따라 정렬하여 새로운 배열을 만든다
* 2차원 이상인 경우 axis인수로 방향결정 (axis로 지정한 축방향을 무시하고 정렬하라는 의미)
* 디폴드값은 -1(가장 안쪽의 차원)

In [47]:
a = np.array([[4, 3, 5], [1, 2, 1]])
a

array([[4, 3, 5],
       [1, 2, 1]])

In [48]:
np.sort(a)

array([[3, 4, 5],
       [1, 1, 2]])

In [49]:
np.sort(a, axis=0) #행끼리 정렬 (하나의 열에서)

array([[1, 2, 1],
       [4, 3, 5]])

In [50]:
np.sort(a, axis=1) #열끼리 정렬 (하나의 행에서) np.sort(a)와 같은 결과

array([[3, 4, 5],
       [1, 1, 2]])

In [51]:
# sort 메서드는 해당 객체의 자료 자체가 변화하는 in-place 메서드이므로 사용할 때 주의
a.sort(axis=1)
a

array([[3, 4, 5],
       [1, 1, 2]])

### 5-2. argsort
자료를 정렬하는 것이 아니라 순서만 알고 싶다면 argsort

In [52]:
a = np.array([4, 3, 1, 2])
g=np.argsort(a)
g

array([2, 3, 1, 0], dtype=int64)

In [53]:
a[g]

array([1, 2, 3, 4])